module DPSS {
	interface game
	{
    boolean createPlayerAccount(in string firstName, in string lastName,in long age, in string userName, in string password, in string IPAddress);
    string playerSignIn(in string userName, in string password, in string IPAddress) ;	
	string playerSignOut(in string userName, in string IPAddress) ;	
	string getPlayerStatus(in string AdminUserName, in string adminPassword, in string IPAddress) ;
	boolean transferAccount(in string userName,in string passWord,in string OldIPAddress,in string NewIPAddress);
	boolean suspendAccount(in string AdminUserName, in string AdminPassword,in string adminIPAddress,in string userNameToSuspend);
		};
};
